import { Capability } from './types';

export const BUSINESS_CAPABILITIES: Capability[] = [
  // ── TIER 1: AI FUNDAMENTALS & UNDERSTANDING (2022–2023) ─────────────
  { id: "T1_01", tier: 1, firstAvailable: "2022-11",
    en: "AI chat assistants for questions and research",
    de: "KI-Chat-Assistenten für Fragen und Recherche",
    examples: { en: "e.g. ChatGPT, Claude.ai, Google Gemini, Microsoft Copilot", de: "z.B. ChatGPT, Claude.ai, Google Gemini, Microsoft Copilot" } },
  { id: "T1_02", tier: 1, firstAvailable: "2022-12",
    en: "AI-powered web search and research",
    de: "KI-gestützte Websuche und Recherche",
    examples: { en: "e.g. Perplexity AI, Bing Copilot, Google AI Overview", de: "z.B. Perplexity AI, Bing Copilot, Google AI Overview" } },
  { id: "T1_03", tier: 1, firstAvailable: "2023-02",
    en: "AI writing and grammar assistance",
    de: "KI-Schreib- und Grammatikhilfe",
    examples: { en: "e.g. Grammarly, LanguageTool, DeepL", de: "z.B. Grammarly, LanguageTool, DeepL" } },

  // ── TIER 2: BASIC TOOLING (2023–2024) ───────────────────────────────
  { id: "T2_01", tier: 2, firstAvailable: "2023-02",
    en: "AI-integrated note-taking and knowledge management",
    de: "KI-integrierte Notizen und Wissensmanagement",
    examples: { en: "e.g. Notion AI, Obsidian AI plugins", de: "z.B. Notion AI, Obsidian AI-Plugins" } },
  { id: "T2_02", tier: 2, firstAvailable: "2023-02",
    en: "AI meeting transcription and summaries",
    de: "KI-Meeting-Transkription und Zusammenfassungen",
    examples: { en: "e.g. Otter.ai, Fireflies, tl;dv, Copilot in Teams", de: "z.B. Otter.ai, Fireflies, tl;dv, Copilot in Teams" } },
  { id: "T2_03", tier: 2, firstAvailable: "2022-09",
    en: "AI image and visual content generation",
    de: "KI-Bild- und visuelle Inhaltsgenerierung",
    examples: { en: "e.g. DALL-E, Midjourney, Stable Diffusion, Canva AI", de: "z.B. DALL-E, Midjourney, Stable Diffusion, Canva AI" } },
  { id: "T2_04", tier: 2, firstAvailable: "2024-02",
    en: "AI-powered team communication",
    de: "KI-gestützte Teamkommunikation",
    examples: { en: "e.g. Slack AI summaries, Teams AI", de: "z.B. Slack AI Zusammenfassungen, Teams AI" } },

  // ── TIER 3: PRODUCTIVE USAGE (2024) ─────────────────────────────────
  { id: "T3_01", tier: 3, firstAvailable: "2023-11",
    en: "AI in office applications — documents, spreadsheets, presentations",
    de: "KI in Office-Anwendungen — Dokumente, Tabellen, Präsentationen",
    examples: { en: "e.g. Copilot in Word/Excel/PowerPoint, Gemini in Docs/Sheets/Slides", de: "z.B. Copilot in Word/Excel/PowerPoint, Gemini in Docs/Sheets/Slides" } },
  { id: "T3_02", tier: 3, firstAvailable: "2023-12",
    en: "AI data analysis from uploaded files",
    de: "KI-Datenanalyse aus hochgeladenen Dateien",
    examples: { en: "Upload CSV/Excel → insights, charts, summaries", de: "CSV/Excel hochladen → Erkenntnisse, Diagramme" } },
  { id: "T3_03", tier: 3, firstAvailable: "2024-05",
    en: "AI projects with file uploads and persistent context",
    de: "KI-Projekte mit Dateien und persistentem Kontext",
    examples: { en: "e.g. ChatGPT Projects, Claude Projects, Google NotebookLM", de: "z.B. ChatGPT Projects, Claude Projects, Google NotebookLM" } },
  { id: "T3_04", tier: 3, firstAvailable: "2024-06",
    en: "Interactive AI artifacts and prototypes",
    de: "Interaktive KI-Artefakte und Prototypen",
    examples: { en: "Build calculators, dashboards, tools by describing them (Claude Artifacts, ChatGPT Canvas)", de: "Rechner, Dashboards, Tools durch Beschreibung bauen (Claude Artifacts, ChatGPT Canvas)" } },

  // ── TIER 4: AUTOMATION & WORKFLOWS (2025) ───────────────────────────
  { id: "T4_01", tier: 4, firstAvailable: "2023-06",
    en: "AI workflow automation",
    de: "KI-Workflow-Automatisierung",
    examples: { en: "e.g. Zapier AI, Make AI, n8n with AI nodes", de: "z.B. Zapier AI, Make AI, n8n mit KI-Bausteinen" } },
  { id: "T4_02", tier: 4, firstAvailable: "2024-01",
    en: "AI ticket and specification writing",
    de: "KI-gestützte Ticket- und Spezifikationserstellung",
    examples: { en: "AI-generated user stories, PRDs, acceptance criteria", de: "KI-generierte User Stories, PRDs, Akzeptanzkriterien" } },
  { id: "T4_03", tier: 4, firstAvailable: "2024-06",
    en: "Automated report generation with AI",
    de: "Automatisierte Report-Erstellung mit KI",
    examples: { en: "Dashboards, monthly reports, KPI summaries generated automatically", de: "Dashboards, Monatsberichte, KPI-Zusammenfassungen automatisch erstellen" } },
  { id: "T4_04", tier: 4, firstAvailable: "2024-03",
    en: "AI-powered document processing",
    de: "KI-gestützte Dokumentenverarbeitung",
    examples: { en: "Invoices, contracts, proposals — automatically analyzed and processed", de: "Rechnungen, Verträge, Angebote — automatisch auswerten und verarbeiten" } },

  // ── TIER 5: ADVANCED AI INTEGRATION (2026) ──────────────────────────
  { id: "T5_01", tier: 5, firstAvailable: "2024-10",
    en: "Computer Use — AI controlling your screen",
    de: "Computer Use — KI steuert deinen Bildschirm",
    examples: { en: "AI navigates apps, fills forms, automates visually (e.g. Anthropic Computer Use, OpenAI Operator)", de: "KI navigiert Apps, füllt Formulare, automatisiert visuell (z.B. Anthropic Computer Use, OpenAI Operator)" } },
  { id: "T5_02", tier: 5, firstAvailable: "2025-06",
    en: "Autonomous AI agents for business processes",
    de: "Autonome KI-Agenten für Geschäftsprozesse",
    examples: { en: "AI agents that independently research, decide, and execute multi-step tasks", de: "KI-Agenten die eigenständig recherchieren, entscheiden und mehrstufige Aufgaben ausführen" } },
  { id: "T5_03", tier: 5, firstAvailable: "2024-11",
    en: "AI connected to internal tools and data sources",
    de: "KI vernetzt mit internen Tools und Datenquellen",
    examples: { en: "AI reads/writes directly to Slack, Jira, CRM, databases (MCP, API integrations)", de: "KI liest/schreibt direkt in Slack, Jira, CRM, Datenbanken (MCP, API-Integrationen)" } },
  { id: "T5_04", tier: 5, firstAvailable: "2025-01",
    en: "AI governance and knowledge transfer in the organization",
    de: "KI-Governance und Wissenstransfer im Unternehmen",
    examples: { en: "AI guidelines, tool standardization, training concepts, best practice documentation", de: "KI-Richtlinien, Tool-Standardisierung, Schulungskonzepte, Best-Practice-Dokumentation" } },
];
