import { Capability } from './types';

export const BUSINESS_CAPABILITIES: Capability[] = [
  // ── TIER 1: TABLE STAKES (2022–2023) ─────────────────────────────
  { id: "T1_01", tier: 1, firstAvailable: "2022-11",
    en: "AI chat assistants for questions and research",
    de: "KI-Chat-Assistenten für Fragen und Recherche",
    examples: { en: "e.g. ChatGPT, Claude.ai, Google Gemini, Microsoft Copilot", de: "z.B. ChatGPT, Claude.ai, Google Gemini, Microsoft Copilot" } },
  { id: "T1_02", tier: 1, firstAvailable: "2022-12",
    en: "AI-powered web search and research",
    de: "KI-gestützte Websuche und Recherche",
    examples: { en: "e.g. Perplexity AI, Bing Copilot, Google AI Overview", de: "z.B. Perplexity AI, Bing Copilot, Google AI Overview" } },
  { id: "T1_03", tier: 1, firstAvailable: "2023-02",
    en: "AI writing and grammar assistance",
    de: "KI-Schreib- und Grammatikhilfe",
    examples: { en: "e.g. Grammarly, LanguageTool, DeepL", de: "z.B. Grammarly, LanguageTool, DeepL" } },

  // ── TIER 2: PRODUCTIVE USAGE (2023–2024) ─────────────────────────
  { id: "T2_01", tier: 2, firstAvailable: "2023-02",
    en: "AI-integrated note-taking and knowledge management",
    de: "KI-integrierte Notizen und Wissensmanagement",
    examples: { en: "e.g. Notion AI, Obsidian AI plugins", de: "z.B. Notion AI, Obsidian AI-Plugins" } },
  { id: "T2_02", tier: 2, firstAvailable: "2023-02",
    en: "AI meeting transcription and summaries",
    de: "KI-Meeting-Transkription und Zusammenfassungen",
    examples: { en: "e.g. Otter.ai, Fireflies, tl;dv, Copilot in Teams", de: "z.B. Otter.ai, Fireflies, tl;dv, Copilot in Teams" } },
  { id: "T2_03", tier: 2, firstAvailable: "2022-09",
    en: "AI image and visual content generation",
    de: "KI-Bild- und visuelle Inhaltsgenerierung",
    examples: { en: "e.g. DALL-E, Midjourney, Stable Diffusion, Canva AI", de: "z.B. DALL-E, Midjourney, Stable Diffusion, Canva AI" } },
  { id: "T2_04", tier: 2, firstAvailable: "2024-02",
    en: "AI-powered team communication",
    de: "KI-gestützte Teamkommunikation",
    examples: { en: "e.g. Slack AI summaries, Teams AI", de: "z.B. Slack AI Zusammenfassungen, Teams AI" } },

  // ── TIER 3: INTEGRATED WORKFLOWS (2024) ──────────────────────────
  { id: "T3_01", tier: 3, firstAvailable: "2023-11",
    en: "AI in office documents — writing and editing",
    de: "KI in Office-Dokumenten — Schreiben und Bearbeiten",
    examples: { en: "e.g. Copilot in Word, Gemini in Docs", de: "z.B. Copilot in Word, Gemini in Docs" } },
  { id: "T3_02", tier: 3, firstAvailable: "2023-11",
    en: "AI in spreadsheets — formulas, analysis, charts",
    de: "KI in Tabellen — Formeln, Analyse, Diagramme",
    examples: { en: "e.g. Copilot in Excel, Gemini in Sheets", de: "z.B. Copilot in Excel, Gemini in Sheets" } },
  { id: "T3_03", tier: 3, firstAvailable: "2023-11",
    en: "AI presentation generation",
    de: "KI-Präsentationserstellung",
    examples: { en: "e.g. Copilot in PowerPoint, Gemini in Slides, Gamma", de: "z.B. Copilot in PowerPoint, Gemini in Slides, Gamma" } },
  { id: "T3_04", tier: 3, firstAvailable: "2023-12",
    en: "AI data analysis from uploaded files",
    de: "KI-Datenanalyse aus hochgeladenen Dateien",
    examples: { en: "Upload CSV/Excel → insights, charts, summaries", de: "CSV/Excel hochladen → Erkenntnisse, Diagramme" } },
  { id: "T3_05", tier: 3, firstAvailable: "2024-05",
    en: "AI desktop apps with persistent context",
    de: "KI-Desktop-Apps mit persistentem Kontext",
    examples: { en: "e.g. ChatGPT Desktop, Claude Desktop", de: "z.B. ChatGPT Desktop, Claude Desktop" } },

  // ── TIER 4: ADVANCED USAGE (2025) ────────────────────────────────
  { id: "T4_01", tier: 4, firstAvailable: "2024-06",
    en: "AI projects with file uploads and persistent context",
    de: "KI-Projekte mit Datei-Uploads und persistentem Kontext",
    examples: { en: "Upload docs → AI remembers across conversations", de: "Dokumente hochladen → KI merkt sich Kontext" } },
  { id: "T4_02", tier: 4, firstAvailable: "2024-06",
    en: "Interactive AI artifacts — apps built in conversation",
    de: "Interaktive KI-Artefakte — Apps aus Konversation",
    examples: { en: "Build calculators, dashboards, tools by describing them", de: "Rechner, Dashboards, Tools durch Beschreibung bauen" } },
  { id: "T4_03", tier: 4, firstAvailable: "2023-06",
    en: "AI workflow automation",
    de: "KI-Workflow-Automatisierung",
    examples: { en: "e.g. Zapier AI, Make AI, automated processes", de: "z.B. Zapier AI, Make AI, automatisierte Prozesse" } },
  { id: "T4_04", tier: 4, firstAvailable: "2024-01",
    en: "AI ticket and specification writing",
    de: "KI-Ticket- und Spezifikationserstellung",
    examples: { en: "AI-generated user stories, PRDs, acceptance criteria", de: "KI-generierte User Stories, PRDs, Akzeptanzkriterien" } },

  // ── TIER 5: FRONTIER (2026) ──────────────────────────────────────
  { id: "T5_01", tier: 5, firstAvailable: "2024-10",
    en: "Computer Use — AI controlling your screen",
    de: "Computer Use — KI steuert Ihren Bildschirm",
    examples: { en: "AI navigates apps, fills forms, automates visually", de: "KI navigiert Apps, füllt Formulare, automatisiert visuell" } },
  { id: "T5_02", tier: 5, firstAvailable: "2025-06",
    en: "Custom AI agents for business processes",
    de: "Benutzerdefinierte KI-Agenten für Geschäftsprozesse",
    examples: { en: "Build AI agents for recurring business tasks", de: "KI-Agenten für wiederkehrende Aufgaben bauen" } },
  { id: "T5_03", tier: 5, firstAvailable: "2024-11",
    en: "AI connected to business tools via integrations",
    de: "KI verbunden mit Business-Tools",
    examples: { en: "AI reads/writes Slack, Jira, CRM, databases", de: "KI liest/schreibt Slack, Jira, CRM, Datenbanken" } },
  { id: "T5_04", tier: 5, firstAvailable: "2025-09",
    en: "AI with persistent memory across sessions",
    de: "KI mit persistentem Gedächtnis",
    examples: { en: "AI remembers preferences, projects, past conversations", de: "KI merkt sich Präferenzen, Projekte, Gespräche" } },
];
