import { Capability } from './types';

export const DEV_CAPABILITIES: Capability[] = [
  // ── TIER 1: AI FUNDAMENTALS & UNDERSTANDING (2022–2023) ──────────
  { id: "T1_01", tier: 1, firstAvailable: "2022-06",
    en: "Inline code completions",
    de: "Inline Code-Vervollständigung",
    examples: { en: "e.g. GitHub Copilot, Cursor Tab, Tabnine, Windsurf", de: "z.B. GitHub Copilot, Cursor Tab, Tabnine, Windsurf" } },
  { id: "T1_02", tier: 1, firstAvailable: "2022-11",
    en: "AI chat for code questions and generation",
    de: "KI-Chat für Code-Fragen und -Generierung",
    examples: { en: "e.g. Copilot Chat, Cursor Chat, ChatGPT, Claude.ai", de: "z.B. Copilot Chat, Cursor Chat, ChatGPT, Claude.ai" } },
  { id: "T1_03", tier: 1, firstAvailable: "2022-11",
    en: "AI-assisted error diagnosis",
    de: "KI-gestützte Fehlerdiagnose",
    examples: { en: "Paste an error or stack trace → get explanation and fix", de: "Fehler oder Stack-Trace einfügen → Erklärung und Fix erhalten" } },
  { id: "T1_04", tier: 1, firstAvailable: "2022-06",
    en: "AI-generated documentation and docstrings",
    de: "KI-generierte Dokumentation und Docstrings",
    examples: { en: "Auto-generated from function signatures via any AI tool", de: "Automatisch generiert aus Funktionssignaturen" } },

  // ── TIER 2: BASIC TOOLING (2023–2024) ────────────────────────────
  { id: "T2_01", tier: 2, firstAvailable: "2023-06",
    en: "Codebase Q&A and exploration",
    de: "Codebase-Fragen und -Erkundung",
    examples: { en: "Ask questions about unfamiliar code, navigate large repos", de: "Fragen an unbekannten Code, große Repos navigieren" } },
  { id: "T2_02", tier: 2, firstAvailable: "2023-11",
    en: "AI-assisted git workflows",
    de: "KI-gestützte Git-Workflows",
    examples: { en: "Commit messages, branch management, PR descriptions", de: "Commit-Nachrichten, Branch-Management, PR-Beschreibungen" } },
  { id: "T2_03", tier: 2, firstAvailable: "2023-12",
    en: "AI code refactoring and transformation",
    de: "KI-gestütztes Code-Refactoring",
    examples: { en: "Rename, restructure, migrate patterns via AI", de: "Umbenennen, Umstrukturieren, Muster migrieren via KI" } },
  { id: "T2_04", tier: 2, firstAvailable: "2023-12",
    en: "AI test generation",
    de: "KI-Testgenerierung",
    examples: { en: "Unit tests with edge cases, integration tests", de: "Unit-Tests mit Randfällen, Integrationstests" } },
  { id: "T2_05", tier: 2, firstAvailable: "2023-01",
    en: "AI-powered code review",
    de: "KI-gestütztes Code-Review",
    examples: { en: "Automated PR review for bugs, style, security", de: "Automatisiertes PR-Review für Bugs, Stil, Sicherheit" } },

  // ── TIER 3: PRODUCTIVE USAGE (2024) ──────────────────────────────
  { id: "T3_01", tier: 3, firstAvailable: "2024-07",
    en: "Multi-file agentic editing",
    de: "Multi-Datei-agentische Bearbeitung",
    examples: { en: "Single prompt → changes across multiple files", de: "Ein Prompt → Änderungen über mehrere Dateien" } },
  { id: "T3_02", tier: 3, firstAvailable: "2024-10",
    en: "Full application generation from descriptions",
    de: "App-Generierung aus Beschreibungen",
    examples: { en: "Describe an app → get working prototype (Bolt, Lovable, v0)", de: "App beschreiben → Prototyp erhalten (Bolt, Lovable, v0)" } },
  { id: "T3_03", tier: 3, firstAvailable: "2024-06",
    en: "Interactive AI artifacts and prototypes",
    de: "Interaktive KI-Artefakte und Prototypen",
    examples: { en: "Build interactive apps, visualizations in conversation", de: "Interaktive Apps, Visualisierungen im Chat erstellen" } },
  { id: "T3_04", tier: 3, firstAvailable: "2024-03",
    en: "AI security scanning and vulnerability detection",
    de: "KI-Sicherheitsscanning und Schwachstellenerkennung",
    examples: { en: "Automated security analysis in PRs and code", de: "Automatisierte Sicherheitsanalyse in PRs und Code" } },
  { id: "T3_05", tier: 3, firstAvailable: "2024-06",
    en: "Architecture analysis and migration assistance",
    de: "Architektur-Analyse und Migrationsunterstützung",
    examples: { en: "Dependency analysis, framework upgrades, ADR generation", de: "Abhängigkeitsanalyse, Framework-Upgrades, ADR-Generierung" } },
  { id: "T3_06", tier: 3, firstAvailable: "2024-06",
    en: "AI-powered incident triage and log analysis",
    de: "KI-gestützte Incident-Triage und Log-Analyse",
    examples: { en: "Automated root cause analysis from logs and alerts", de: "Automatisierte Ursachenanalyse aus Logs und Alerts" } },

  // ── TIER 4: AUTOMATION & WORKFLOWS (2025) ────────────────────────
  { id: "T4_01", tier: 4, firstAvailable: "2023-06",
    en: "Custom AI instruction files",
    de: "Benutzerdefinierte KI-Instruktionsdateien",
    examples: { en: "CLAUDE.md, .cursorrules, copilot-instructions.md", de: "CLAUDE.md, .cursorrules, copilot-instructions.md" } },
  { id: "T4_02", tier: 4, firstAvailable: "2024-11",
    en: "MCP server integrations",
    de: "MCP-Server-Integrationen",
    examples: { en: "Connect AI to Slack, Notion, databases, APIs", de: "KI mit Slack, Notion, Datenbanken, APIs verbinden" } },
  { id: "T4_03", tier: 4, firstAvailable: "2025-05",
    en: "Background and asynchronous AI agents",
    de: "Hintergrund- und asynchrone KI-Agenten",
    examples: { en: "Assign issue → AI works autonomously → opens PR", de: "Issue zuweisen → KI arbeitet autonom → erstellt PR" } },
  { id: "T4_04", tier: 4, firstAvailable: "2024-02",
    en: "AI memory and persistent context across sessions",
    de: "KI-Gedächtnis und persistenter Kontext",
    examples: { en: "AI remembers project patterns and preferences", de: "KI merkt sich Projektmuster und Präferenzen" } },
  { id: "T4_05", tier: 4, firstAvailable: "2025-10",
    en: "AI-assisted merge conflict resolution",
    de: "KI-gestützte Merge-Konfliktlösung",
    examples: { en: "AI understands both sides and resolves conflicts", de: "KI versteht beide Seiten und löst Konflikte" } },
  { id: "T4_06", tier: 4, firstAvailable: "2024-06",
    en: "Checkpoint and undo systems for AI changes",
    de: "Checkpoint- und Undo-Systeme für KI-Änderungen",
    examples: { en: "Automatic snapshots, instant rollback of AI edits", de: "Automatische Snapshots, sofortiges Rollback" } },

  // ── TIER 5: ADVANCED AI INTEGRATION (2026) ───────────────────────
  { id: "T5_01", tier: 5, firstAvailable: "2025-02",
    en: "Custom slash commands and reusable AI skills",
    de: "Benutzerdefinierte Slash-Commands und KI-Skills",
    examples: { en: "Build reusable prompt workflows, share across team", de: "Wiederverwendbare Prompt-Workflows, im Team teilen" } },
  { id: "T5_02", tier: 5, firstAvailable: "2025-06",
    en: "Hooks and event-driven AI automation",
    de: "Hooks und ereignisgesteuerte KI-Automatisierung",
    examples: { en: "Trigger scripts on AI events (pre-commit, post-edit)", de: "Skripte bei KI-Events auslösen" } },
  { id: "T5_03", tier: 5, firstAvailable: "2026-02",
    en: "Agent teams — multi-agent coordination",
    de: "Agent-Teams — Multi-Agenten-Koordination",
    examples: { en: "Multiple AI agents collaborate, communicate, share findings", de: "Mehrere KI-Agenten arbeiten zusammen" } },
  { id: "T5_04", tier: 5, firstAvailable: "2024-10",
    en: "Computer Use — AI controlling browser and desktop",
    de: "Computer Use — KI steuert Browser und Desktop",
    examples: { en: "AI interprets screen, clicks, fills forms, navigates apps", de: "KI interpretiert Bildschirm, klickt, füllt Formulare" } },
  { id: "T5_05", tier: 5, firstAvailable: "2025-10",
    en: "Git worktrees for parallel AI development",
    de: "Git-Worktrees für parallele KI-Entwicklung",
    examples: { en: "Multiple AI agents on separate branches simultaneously", de: "Mehrere KI-Agenten auf separaten Branches gleichzeitig" } },
];
